mode: localhost
port: 8088
name: MyApp
version: 1.0.0
starttime: "2023-10-01T00:00:00Z"
machineid: 1
logconfig:
  level: info
  filename: app.log
  maxsize: 10
  maxline: 0
  maxage: 7
  maxbackups: 3
mysqlconfig:
  host: localhost
  port: 3306
  user: root
  password: password
  dbname: yiyuser
  maxopenconns: 100
  maxidleconns: 10
